### ISSUE TITLE
0:59: Output displays a tuple, not a list

### ISSUE THREAD

**Issue by mathresearch** [udacity/aipnd_issues_tracker#13] opened 2018-04-05 08:01 UTC

**Comment by j-staab** [comment] 2018-05-15 20:16
Hi @mathresearch ,
Thanks for raising  this issue.  If you could provide more details about where the "output displays a tuple, not a list".  Which lesson and section this happens within the video at 0:59.
Thanks for the clarification.
-Jennifer

**Comment by j-staab** [comment] 2018-05-15 20:18
Hi @mathresearch , 
I just saw ticket # 14 - seems like this happens in Lesson2.3 #25 - if I am correct in this assumption let me know and I will close this ticket since ticket # 14 provides the Lesson location detail.
Thanks!
-Jennifer

**Comment by ronny-udacity** [comment] 2018-09-12 16:41
duplicate of issue #14

**Closed by ronny-udacity** 2018-09-12 16:41 UTC
