### ISSUE TITLE
Lesson 2.17 Are you in OR not in?

### ISSUE THREAD

**Issue by lawkai** [udacity/aipnd_issues_tracker#10] opened 2018-04-04 15:56 UTC
typo in this line:
>>> 'in` in 'this is a string'
True

the back tick should be a single quote.

**Comment by j-staab** [comment] 2018-04-24 22:16
Hi @lawkai, 
I really appreciate that you raised this issue, but I am having trouble locating where the issue occurs.  In Lesson 2. Data Types and Operators - section 17. Quiz: Type and Type conversion - I couldn't find the issue.

In Lesson 2. Data Types and Operators - section 13. Strings -  I see 
>>> my_string = 'this is a string!'
>>> my_string2 = " this is also a string!!!"
But I didn't see any back-ticks.  It could be this issue was already addressed or that I have the wrong section.  Would you please clarify where this typo occurs?

Thanks in advance for the help!

**Comment by lawkai** [comment] 2018-04-26 14:33
I might have a typo in the issue unless there is a recent change in the chapters? Anyway... it can be find in Lesson 2.21 
Screencap for your reference:
![screen shot 2018-04-26 at 10 31 55 pm](https://user-images.githubusercontent.com/240803/39312268-c63f45e4-49a1-11e8-993d-f5cdeba7c5e3.png)

**Comment by j-staab** [comment] 2018-04-26 15:55
Hi @lawkai, 
I really appreciate your help with catching this typo, you should find it is now fixed in the classroom.  Thanks again for the screen capture - that totally helped me fix the typo!  Edits are on-going so things could have changed since when you saw them last.  Providing a screen capture really helps narrow down where the issue is located. Good Luck with the rest of the ND -- and if you find any other typos or issues - please let us know!

**Closed** 2018-04-26 15:55 UTC
Labels: in progress
